### ISSUE TITLE
Try with Keycloakify

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-account-v1#3]
@garronej

In order to use the PR and this with Keycloakify, we need to:
1. Update Keycloakify to use `account-v1` as its parent theme. Currently you are using `keycloak` as the parent theme. If you are actually using any of the `keycloak` parent theme files, you need to bring those into Keycloakify, as this only has the `base` theme files
2. The jar produced by this project would need to get bundled with Keycloakify (either deployed together, or using maven shade to merge them together)

To test, it should be sufficient to follow the instructions in the [README](https://github.com/xgp/keycloak-account-v1/blob/main/README.md) and add a Keycloakify built jar. Let me know if I can help you with it.

**Comment by garronej** [comment]
Hello @xgp,  

Thank you, it's very clear, I'll get on it ASAP!

**Comment by garronej** [comment]
Hello @xgp,

I've just released a candidate, Keycloakify `7.16.0-rc.1`, that I believe incorporates all the instructions you provided.

To test this, please follow these steps:

```bash
git clone https://github.com/keycloakify/keycloakify-starter
cd keycloakify-starter
yarn install
yarn build-keycloak-theme
```

Once done, could you share your feedback on the contents of the `/build_keycloak` directory?

If there are any nuances or complexities, I'm open to scheduling a brief meeting to discuss them further.

On a side note, I'm also contemplating how to develop a theme compatible with both Keycloak versions prior to v22 and subsequent versions. I'll delve deeper into this soon.

Your assistance has been invaluable. Thank you once again!

**Comment by xgp** [comment]
When I follow the instructions, the jar that gets built in `/build_keycloak/target/keycloakify-starter-keycloak-theme-4.6.5.jar` isn't complete. However, if I go into the `/build_keycloak` directory and run `mvn clean install` the jar is fine.

After that, I run it with the keycloak version in the PR, I get:
```
2023-08-11 17:13:05,919 WARN  [org.keycloak.theme.DefaultThemeManager] (executor-thread-4) Not found theme 'common/account-v1-keycloak' referenced as import of theme 'account-v1-keycloak'. Unable to load ACCOUNT theme 'account-v1-keycloak' due to this.
```

I believe this is due to the lack of a declaration of the `common` theme in the `keycloak-themes.json` file. When I added that and rebuilt, all of the themes load:

![image](https://github.com/xgp/keycloak-account-v1/assets/244253/e7200ef2-758b-4038-95e4-cce855b63f40)

However, the current mechanism I had for loading the `AccountResourceProvider` only used the theme name and parent theme name. The mechanism of using a class name in the `theme.properties` file that [Stan suggested](https://github.com/keycloak/keycloak/pull/22317#pullrequestreview-1567993818) will work better, so I had to add `accountResourceProvider=org.keycloak.services.resources.account.AccountFormService` to all of those files. 

After doing that, it seems to load with the `keycloakify-starter` and `keycloakify-starter-variant-1`:
![image](https://github.com/xgp/keycloak-account-v1/assets/244253/10d0f696-b264-4662-88b9-8892b0246994)

But there are some problems rendering some of the tabs, as it appears the `patternfly` css files are returning 404:
![image](https://github.com/xgp/keycloak-account-v1/assets/244253/0261b836-21de-4d1a-a910-27d69d133358)
They are trying to load from `/resources/x8roa/common/account-v1-keycloak/node_modules/patternfly/dist/css/patternfly.min.css` and `/resources/x8roa/common/account-v1-keycloak/node_modules/patternfly/dist/css/patternfly-additions.min.css`

-----

So, concretely, we need to:
1. Figure out why your `yarn build-keycloak-theme` isn't building the jar correctly
2. Add the `common` theme in your `keycloak-themes.json` file
3. add `accountResourceProvider=org.keycloak.services.resources.account.AccountFormService` to all of the `theme.properties` files
4. make sure the the patternfly css is in the right place

**Comment by garronej** [comment]
@xgp Thanks a lot for the update!  

I'll update this ASAP. Sorry I didn't find time to do it earlyer.

**Comment by garronej** [comment]
Hello @xgp,

I'm actively working on resolving the issue related to resource resolution over the weekend. I have a solid understanding of the problem at hand and am confident that I can tackle it effectively.

However, I'm facing some difficulties with building the JAR file using `mvn`. Below is a screenshot of the issue I'm encountering:

![Maven Build Issue](https://github.com/xgp/keycloak-account-v1/assets/6702424/585f68a2-e759-4ca9-9e31-532d8670f0e9)

Would you be able to provide some guidance or hints to help resolve this Maven build issue?

Once I have a working JAR built with Maven, I'll proceed to investigate why our in-house bundler is not functioning as expected. On a related note, for those interested, it's worth mentioning that [Maven can be chosen as an alternative build option](https://docs.keycloakify.dev/build-options#bundler) to our in-house bundler.

Thank you for your assistance!

Best regards,
[Your Username]

**Comment by xgp** [comment]
You have to build my branch of the Keycloak project for that jar/version to be available in your local maven repo.

**Comment by garronej** [comment]
Just a quick update: I'm working on my side of things, almost there. 👍🏻

**Comment by garronej** [comment]
Hello @xgp,  

How are you doing? I think I've done everything that needed to do on my side.  
If you could have a look and tell me if everything look good to you.  

```bash
git clone https://github.com/keycloakify/keycloakify-starter
cd keycloakify-starter
git checkout v9
yarn install
yarn build-keycloak-theme
```  

Thanks a lot!

**Comment by garronej** [comment]
Of course, @xgp, I understand that you're working diligently to finalize the main PR based on the maintainers' feedback. Take your time; I'll be here to act on your feedback as soon as you're ready.

**Comment by xgp** [comment]
@garronej I've updated this repo based on the merge that happened to keycloak main here https://github.com/keycloak/keycloak/pull/22317
This should now be a usable base theme for Keycloakify and other themes that are extending the account theme. It should be sufficient to deploy this jar and specify `parent=account-v1` in your `theme.properties` in order to use the resources that are compatible with the "old" account theme. Let me know when you have a chance to update your test, and I will try to run it.

**Comment by garronej** [comment]
Thanks again for your work @xgp,  
I'll try to spare some time this week end!

**Comment by garronej** [comment]
Hello @xgp!  

I've finally updated Keycloakify v9.  

It sill wont build it fails on `mvn package`, maybe it's expected, would you have a look?   

```bash
git clone https://github.com/keycloakify/keycloakify-starter
cd keycloakify-starter
git checkout v9
yarn install
yarn build-keycloak-theme
```

You can have a look at what's generated in `/build_keyloak` and tell me if it looks good to you?  

I'm a little worried [about this](https://github.com/keycloakify/keycloakify/blob/a6dcfe2c87852416b44ecc9f86f049c56d9656bb/src/bin/keycloakify/generateJavaStackFiles/generateJavaStackFiles.ts#L51) though.  
At the moment I have hardcoded the version to 23.0.0 but I hope this version number does not mean that we will have to know at build time on which version ok Keycloak the theme will be deployed...  

Thanks in advance for your help!

**Comment by xgp** [comment]
@garronej Regarding the worry about version number, the java parts of the extension have to compile against a version of keycloak that contains the patches. That means *at least* version `23.0.0`. Assuming no breaking changes are made in keycloak, then it will not have to change, as it is just a compile-time dependency.

However, I don't think it's necessary for you to include all of the java anymore, now that the base theme I wrote is released. I think it should be sufficient to have a simple `pom.xml` like this:

```xml
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>dev.keycloakify.starter.keycloak</groupId>
  <artifactId>keycloakify-starter-keycloak-theme</artifactId>
  <version>4.9.1</version>
  <name>keycloakify-starter-keycloak-theme</name>
  <description />
  <packaging>jar</packaging>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
	<version>3.5.1</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <dependencies>
    <dependency>
      <groupId>io.phasetwo.keycloak</groupId>
      <artifactId>keycloak-account-v1</artifactId>
      <version>0.1</version>
    </dependency>
  </dependencies>
</project>
```
This makes it depend on the `keycloak-account-v1` library that I released, and then uses the [Maven Shade Plugin](https://maven.apache.org/plugins/maven-shade-plugin/) to package that along with your custom themes. 
 
After building with `yarn install && yarn build-keycloak-theme` as you described above, I replaced the `pom.xml` in the `build_keyloak` dir, ran `rm -rf src/main/java` and `mvn clean install`. I was then able to run and see all the themes by altering the startup script to look like this:
```bash
#!/usr/bin/env bash

docker rm keycloak-testing-container || true

cd "/home/garth/projects/saascrud/keycloakify-starter/build_keycloak"

docker run \
   -p 8080:8080 \
   --name keycloak-testing-container \
   -e KEYCLOAK_ADMIN=admin \
   -e KEYCLOAK_ADMIN_PASSWORD=admin \
   -v ${PWD}/target/keycloakify-starter-keycloak-theme-4.9.1.jar:/opt/keycloak/providers/keycloakify-starter-keycloak-theme-4.9.1.jar \
   -it quay.io/keycloak/keycloak:23.0.0 \
   start-dev --features=declarative-user-profile
```
Let me know if you're able to get the same result, or, if not, the specific error you are seeing. 

Thanks again for all your work on this!
