### ISSUE TITLE
Add back keycloak-v1 theme?

### ISSUE THREAD

**Issue by xgp** [p2-inc/keycloak-account-v1#6]
This is currently just the `base` theme, so that you can use it with your extensions (e.g. Keycloakify). Does anyone want the original `keycloak` account theme?

**Comment by garronej** [comment]
Hi @xgp,

I believe this issue can be closed. The [section here](https://github.com/p2-inc/keycloak-account-v1?tab=readme-ov-file#updating-your-account-theme-for-keycloak-version-23-and-beyond) explains how to use this module depending on whether it extends the base theme or the Keycloak theme.
